import pygame

TITLE = "Square Wars"

LOGICAL_WIDTH = 64
LOGICAL_HEIGHT = 64
LOGICAL_SIZE = (LOGICAL_WIDTH, LOGICAL_HEIGHT)

DISPLAY_FLAGS = pygame.SCALED
FULLSCREEN = False

TEAM_NONE = -1
TEAM_ORANGE = 0
TEAM_BROWN = 1

BLANK_COLOR = "#d4d3d1"
ORANGE_COLOR = "#c95937"
BROWN_COLOR = "#5a3428"

FPS = 0
# FPS = 60
